#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# OpenDSP Manager
# Copyright (C) 2018 Romulo Silva <contact@midilab.co>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License see the doc/GPL.txt file.
from opendspd import opendspd

# Data bank paths
USER_DATA = "/home/opendsp/data"

if __name__ == '__main__':

    # get opendsp core instance
    opendsp = opendspd.Core(USER_DATA)

    # initing opendsp
    opendsp.init()

    # daemonize us \_/
    opendsp.run()
